window.SolveDeskSeed = (() => {
  const categories = [
    "Sistema interno",
    "Impressão digital",
    "Flexografia",
    "Arquivos de cliente",
    "Rede e internet",
    "Computadores",
    "Software",
    "Hardware",
    "ERP",
    "Atendimento",
    "Produção",
    "Pré-impressão",
    "Financeiro",
    "Comercial",
    "Erro humano",
    "Processo interno",
    "Urgência crítica",
    "Outro"
  ];

  const sectors = [
    "Gestão de TI",
    "Pré-impressão",
    "Produção",
    "Flexografia",
    "Impressão digital",
    "Financeiro",
    "Comercial",
    "Atendimento",
    "Expedição",
    "Administração"
  ];

  const roles = [
    {
      id: "admin",
      name: "Administrador",
      hint: "Edita tudo, configura categorias, usuários e relatórios."
    },
    {
      id: "manager",
      name: "Gestor de TI",
      hint: "Aprova soluções, acompanha produtividade e revisões."
    },
    {
      id: "technician",
      name: "Técnico",
      hint: "Registra, resolve e documenta problemas técnicos."
    },
    {
      id: "attendant",
      name: "Atendente",
      hint: "Abre problemas e consulta soluções aprovadas."
    },
    {
      id: "viewer",
      name: "Visualizador",
      hint: "Consulta a base de conhecimento."
    }
  ];

  const checklists = {
    "Rede e internet": [
      "Verificar modem",
      "Verificar roteador",
      "Testar cabo",
      "Verificar DNS",
      "Reiniciar equipamento",
      "Testar outro computador",
      "Registrar resultado"
    ],
    "Arquivos de cliente": [
      "Conferir extensão do arquivo",
      "Verificar resolução",
      "Verificar cores",
      "Verificar sangria",
      "Verificar fonte",
      "Verificar compatibilidade",
      "Registrar ajuste feito"
    ],
    "Hardware": [
      "Conferir cabos",
      "Testar tomada ou nobreak",
      "Verificar conexões internas",
      "Testar peça reserva",
      "Registrar patrimônio afetado"
    ],
    "ERP": [
      "Conferir usuário e permissões",
      "Validar pedido ou lançamento",
      "Testar em outro navegador",
      "Verificar integração",
      "Registrar evidência"
    ]
  };

  const problems = [
    {
      id: "PRB-2026-001",
      title: "Cliente não consegue enviar arquivo para produção",
      client: "Cliente Exemplo",
      sector: "Pré-impressão",
      category: "Arquivos de cliente",
      urgency: "Alta",
      impact: "Produção parada",
      status: "Validado",
      occurredAt: "2026-06-10",
      owner: "Mariana Lopes",
      description: "O cliente informou que o arquivo enviado não abre corretamente no sistema de pré-impressão.",
      symptoms: "Arquivo corrompido, erro ao abrir, produção não consegue seguir.",
      involved: "Software de pré-impressão e fluxo de produção digital",
      probableCause: "Arquivo exportado em versão incompatível ou com fonte ausente.",
      confirmedCause: "PDF gerado sem fontes convertidas em curvas e com sangria fora do padrão.",
      solution: "Solicitar novo envio em PDF/X-1a, conferir fontes convertidas em curvas, validar sangria e testar abertura antes de liberar para produção.",
      steps: [
        "Baixar o arquivo recebido.",
        "Testar abertura no software de pré-impressão.",
        "Conferir extensão e versão do arquivo.",
        "Verificar fontes, sangria, cores e resolução.",
        "Solicitar reenvio corrigido ao cliente.",
        "Validar o novo arquivo.",
        "Registrar solução no sistema.",
        "Marcar como resolvido."
      ],
      dontDo: "Não liberar arquivo sem teste de abertura e sem conferência de sangria.",
      prevention: "Criar guia padrão de envio de arquivos para clientes.",
      timeSpent: 85,
      notes: "Cliente recebeu checklist de envio.",
      tags: ["arquivo", "pdf", "pré-impressão", "produção"],
      related: ["PRB-2026-004"],
      solutionState: "Solução definitiva",
      tested: true,
      canRecur: true,
      assetId: "",
      accesses: 38,
      timeline: [
        ["Registrado", "10/06/2026 08:42", "Chamado aberto pelo atendimento."],
        ["Recebido", "10/06/2026 08:55", "Pré-impressão confirmou erro de abertura."],
        ["Causa encontrada", "10/06/2026 09:34", "Fontes e sangria fora do padrão."],
        ["Solução aplicada", "10/06/2026 10:05", "Novo arquivo validado."],
        ["Validado", "10/06/2026 10:20", "Produção liberada."]
      ],
      comments: [
        {
          author: "João Pereira",
          role: "Técnico",
          text: "Checklist interno atualizado com padrão PDF/X-1a.",
          status: "Revisado",
          createdAt: "2026-06-10 11:02"
        }
      ],
      attachments: ["evidencia-pre-impressao.png"],
      history: ["Criado por Mariana Lopes", "Validado por Gestão de TI"],
      month: "Jun/2026"
    },
    {
      id: "PRB-2026-002",
      title: "Internet caiu no setor de flexografia",
      client: "Setor interno",
      sector: "Flexografia",
      category: "Rede e internet",
      urgency: "Crítica",
      impact: "Setor sem acesso ao ERP e arquivos",
      status: "Resolvido",
      occurredAt: "2026-06-11",
      owner: "Rafael Nunes",
      description: "A equipe perdeu acesso à internet e ao servidor de arquivos durante troca de turno.",
      symptoms: "ERP não carrega, compartilhamento de rede indisponível e impressoras de rede sem resposta.",
      involved: "Switch SW-FLX-02, roteador principal e cabeamento do setor.",
      probableCause: "Loop ou falha em cabo de rede ligado ao switch.",
      confirmedCause: "Cabo danificado causou instabilidade no switch do setor.",
      solution: "Isolar porta instável, substituir cabo e reiniciar switch após salvar configuração.",
      steps: [
        "Confirmar se a queda é geral ou local.",
        "Verificar LEDs do switch.",
        "Desconectar portas com oscilação.",
        "Substituir cabo danificado.",
        "Reiniciar switch.",
        "Testar ERP, internet e servidor de arquivos."
      ],
      dontDo: "Não reiniciar todos os equipamentos antes de identificar a porta instável.",
      prevention: "Mapear cabeamento do setor e etiquetar portas críticas.",
      timeSpent: 45,
      notes: "Manter cabos reservas no armário de TI.",
      tags: ["rede", "internet", "switch", "flexografia"],
      related: [],
      solutionState: "Testada",
      tested: true,
      canRecur: true,
      assetId: "AST-004",
      accesses: 24,
      timeline: [
        ["Registrado", "11/06/2026 14:08", "Gestor da flexografia sinalizou parada."],
        ["Testes", "11/06/2026 14:16", "Ping local falhando em vários PCs."],
        ["Causa encontrada", "11/06/2026 14:31", "Porta 12 oscilando."],
        ["Solução aplicada", "11/06/2026 14:48", "Cabo trocado e switch estabilizado."],
        ["Validado", "11/06/2026 14:55", "Setor voltou ao normal."]
      ],
      comments: [
        {
          author: "Rafael Nunes",
          role: "Técnico",
          text: "Sugiro revisar todos os patch cords antigos do setor.",
          status: "Pendente",
          createdAt: "2026-06-11 15:10"
        }
      ],
      attachments: ["foto-switch-flx.jpg"],
      history: ["Vinculado ao recurso SW-FLX-02"],
      month: "Jun/2026"
    },
    {
      id: "PRB-2026-003",
      title: "Pedido aprovado não aparece no ERP",
      client: "Comercial interno",
      sector: "Comercial",
      category: "ERP",
      urgency: "Média",
      impact: "Atraso no faturamento",
      status: "Em análise",
      occurredAt: "2026-06-13",
      owner: "Camila Rocha",
      description: "Pedido consta como aprovado na planilha comercial, mas não aparece no painel do ERP.",
      symptoms: "Número do pedido inexistente no ERP e divergência entre planilha e sistema.",
      involved: "ERP, planilha de pedidos e integração diária.",
      probableCause: "Falha de sincronização ou campo obrigatório vazio.",
      confirmedCause: "Campo de condição de pagamento veio vazio na importação.",
      solution: "Corrigir condição de pagamento na origem e reprocessar integração do pedido.",
      steps: [
        "Conferir número do pedido na planilha.",
        "Validar campos obrigatórios.",
        "Corrigir condição de pagamento.",
        "Reprocessar integração.",
        "Confirmar pedido no ERP."
      ],
      dontDo: "Não cadastrar pedido manualmente antes de conferir a integração.",
      prevention: "Adicionar validação obrigatória antes do envio ao ERP.",
      timeSpent: 60,
      notes: "Aguardando validação do financeiro.",
      tags: ["erp", "pedido", "integração"],
      related: [],
      solutionState: "Precisa revisar",
      tested: false,
      canRecur: true,
      assetId: "",
      accesses: 16,
      timeline: [
        ["Registrado", "13/06/2026 09:12", "Comercial abriu chamado."],
        ["Testes", "13/06/2026 09:35", "Integração simulada com log."],
        ["Causa encontrada", "13/06/2026 10:10", "Campo obrigatório vazio."]
      ],
      comments: [],
      attachments: ["log-integracao.txt"],
      history: ["Aguardando validação"],
      month: "Jun/2026"
    },
    {
      id: "PRB-2026-004",
      title: "Arte com cores divergentes na impressão digital",
      client: "Cliente Ápice",
      sector: "Impressão digital",
      category: "Impressão digital",
      urgency: "Alta",
      impact: "Risco de retrabalho",
      status: "Resolvido",
      occurredAt: "2026-05-28",
      owner: "Bruno Alves",
      description: "A prova impressa apresentou diferença de cor em relação ao arquivo aprovado.",
      symptoms: "Tons de azul saindo arroxeados e áreas escuras sem contraste.",
      involved: "Impressora digital, perfil de cor e arquivo do cliente.",
      probableCause: "Perfil RGB enviado para fluxo CMYK sem conversão controlada.",
      confirmedCause: "Arquivo original estava em RGB e sem perfil ICC incorporado.",
      solution: "Converter arquivo para CMYK com perfil adequado, gerar prova e registrar aprovação.",
      steps: [
        "Conferir perfil de cor do arquivo.",
        "Converter para CMYK com perfil aprovado.",
        "Gerar prova controlada.",
        "Comparar com referência do cliente.",
        "Registrar aprovação antes da tiragem."
      ],
      dontDo: "Não imprimir tiragem final direto de arquivo RGB.",
      prevention: "Padronizar conferência de perfil de cor na entrada.",
      timeSpent: 70,
      notes: "Criado alerta para arquivos RGB.",
      tags: ["cor", "impressão", "rgb", "cmyk"],
      related: ["PRB-2026-001"],
      solutionState: "Aprovada",
      tested: true,
      canRecur: true,
      assetId: "AST-002",
      accesses: 42,
      timeline: [
        ["Registrado", "28/05/2026 13:20", "Produção sinalizou divergência."],
        ["Testes", "28/05/2026 13:45", "Prova comparada com arquivo."],
        ["Solução aplicada", "28/05/2026 14:30", "Perfil corrigido."],
        ["Validado", "28/05/2026 15:10", "Cliente aprovou nova prova."]
      ],
      comments: [],
      attachments: ["comparativo-cores.pdf"],
      history: ["Transformado em procedimento interno"],
      month: "Mai/2026"
    },
    {
      id: "PRB-2026-005",
      title: "Monitor sem imagem na pré-impressão",
      client: "Setor interno",
      sector: "Pré-impressão",
      category: "Hardware",
      urgency: "Média",
      impact: "Estação de trabalho limitada",
      status: "Validado",
      occurredAt: "2026-06-14",
      owner: "João Pereira",
      description: "Monitor principal não exibia imagem ao ligar a estação.",
      symptoms: "LED ligado, tela preta e sem sinal de vídeo.",
      involved: "Monitor Dell 24 polegadas, cabo HDMI e estação gráfica.",
      probableCause: "Cabo HDMI frouxo ou defeituoso.",
      confirmedCause: "Cabo HDMI com mau contato no conector.",
      solution: "Trocar cabo HDMI, testar em outra porta e atualizar histórico do monitor.",
      steps: [
        "Testar outro cabo HDMI.",
        "Testar outra porta de vídeo.",
        "Verificar entrada selecionada no monitor.",
        "Registrar troca do cabo no inventário.",
        "Validar imagem por 10 minutos."
      ],
      dontDo: "Não descartar monitor antes de testar cabo e porta.",
      prevention: "Manter cabos HDMI reservas e revisar conectores mensalmente.",
      timeSpent: 25,
      notes: "Monitor segue em uso.",
      tags: ["monitor", "hdmi", "pré-impressão"],
      related: [],
      solutionState: "Solução definitiva",
      tested: true,
      canRecur: true,
      assetId: "AST-001",
      accesses: 31,
      timeline: [
        ["Registrado", "14/06/2026 08:15", "Usuário reportou tela preta."],
        ["Testes", "14/06/2026 08:22", "Cabo testado em outro monitor."],
        ["Solução aplicada", "14/06/2026 08:35", "Cabo substituído."],
        ["Validado", "14/06/2026 08:40", "Equipamento estabilizado."]
      ],
      comments: [],
      attachments: [],
      history: ["Vinculado ao patrimônio TI-034"],
      month: "Jun/2026"
    }
  ];

  const assets = [
    {
      id: "AST-001",
      name: "Monitor Dell 24 polegadas",
      type: "Monitor",
      code: "TI-034",
      serial: "DL-P2419H-8842",
      brand: "Dell",
      model: "P2419H",
      sector: "Pré-impressão",
      user: "João Pereira",
      acquiredAt: "2024-03-12",
      condition: "Bom",
      status: "Em uso",
      notes: "Monitor já teve problema de cabo HDMI frouxo.",
      photos: ["monitor-ti-034.jpg"],
      invoice: "nf-monitor-034.pdf",
      maintenance: [
        ["14/06/2026", "Troca do cabo HDMI", "Resolvido"],
        ["10/06/2026", "Verificação preventiva", "Ok"]
      ],
      linkedProblems: ["PRB-2026-005"],
      tickets: ["PRB-2026-005"],
      lastCheck: "2026-06-10",
      replacementForecast: "2028-03-12",
      quantity: 1,
      available: 0,
      inUse: 1,
      defective: 0,
      minStock: 0,
      storage: "Pré-impressão"
    },
    {
      id: "AST-002",
      name: "Impressora Digital HP Latex",
      type: "Impressora",
      code: "TI-018",
      serial: "HP-LTX-2239",
      brand: "HP",
      model: "Latex 700",
      sector: "Impressão digital",
      user: "Bruno Alves",
      acquiredAt: "2023-08-05",
      condition: "Regular",
      status: "Em manutenção",
      notes: "Revisar calibração de cor quinzenalmente.",
      photos: ["hp-latex.jpg"],
      invoice: "nf-hp-latex.pdf",
      maintenance: [
        ["28/05/2026", "Recalibração de perfil", "Concluída"],
        ["04/05/2026", "Limpeza de cabeçote", "Concluída"]
      ],
      linkedProblems: ["PRB-2026-004"],
      tickets: ["PRB-2026-004"],
      lastCheck: "2026-06-01",
      replacementForecast: "2027-12-01",
      quantity: 1,
      available: 0,
      inUse: 1,
      defective: 0,
      minStock: 0,
      storage: "Impressão digital"
    },
    {
      id: "AST-003",
      name: "Notebook Lenovo ThinkPad",
      type: "Notebook",
      code: "TI-052",
      serial: "LNV-T14-5521",
      brand: "Lenovo",
      model: "ThinkPad T14",
      sector: "Comercial",
      user: "Camila Rocha",
      acquiredAt: "2025-01-20",
      condition: "Bom",
      status: "Emprestado",
      notes: "Emprestado para visita técnica comercial.",
      photos: [],
      invoice: "nf-thinkpad-052.pdf",
      maintenance: [],
      linkedProblems: [],
      tickets: [],
      lastCheck: "2026-05-30",
      replacementForecast: "2028-01-20",
      loan: {
        person: "Camila Rocha",
        sector: "Comercial",
        start: "2026-06-01",
        due: "2026-06-12",
        outCondition: "Bom",
        returnCondition: "",
        notes: "Aguardando devolução para conferência."
      },
      quantity: 1,
      available: 0,
      inUse: 1,
      defective: 0,
      minStock: 0,
      storage: "Comercial"
    },
    {
      id: "AST-004",
      name: "Switch Flexografia 24 portas",
      type: "Switch",
      code: "TI-061",
      serial: "SW-FLX-02-8821",
      brand: "TP-Link",
      model: "JetStream 24p",
      sector: "Flexografia",
      user: "Setor Flexografia",
      acquiredAt: "2022-09-18",
      condition: "Regular",
      status: "Em uso",
      notes: "Porta 12 apresentou oscilação por cabo danificado.",
      photos: ["switch-flx.jpg"],
      invoice: "nf-switch-061.pdf",
      maintenance: [
        ["11/06/2026", "Isolamento de porta e troca de cabo", "Resolvido"]
      ],
      linkedProblems: ["PRB-2026-002"],
      tickets: ["PRB-2026-002"],
      lastCheck: "2026-06-11",
      replacementForecast: "2027-09-18",
      quantity: 1,
      available: 0,
      inUse: 1,
      defective: 0,
      minStock: 0,
      storage: "Rack Flexografia"
    },
    {
      id: "AST-005",
      name: "Cabo HDMI 2m",
      type: "Cabo HDMI",
      code: "STK-HDMI-2M",
      serial: "",
      brand: "Diversos",
      model: "2 metros",
      sector: "Estoque TI",
      user: "",
      acquiredAt: "2026-04-02",
      condition: "Novo",
      status: "Disponível",
      notes: "Item de estoque para substituições rápidas.",
      photos: [],
      invoice: "nf-cabos-hdmi.pdf",
      maintenance: [],
      linkedProblems: ["PRB-2026-005"],
      tickets: [],
      lastCheck: "2026-06-15",
      replacementForecast: "",
      quantity: 8,
      available: 2,
      inUse: 5,
      defective: 1,
      minStock: 3,
      storage: "Armário TI"
    },
    {
      id: "AST-006",
      name: "Mouse sem fio Logitech",
      type: "Mouse",
      code: "STK-MOU-LOG",
      serial: "",
      brand: "Logitech",
      model: "M170",
      sector: "Estoque TI",
      user: "",
      acquiredAt: "2026-02-18",
      condition: "Bom",
      status: "Disponível",
      notes: "Estoque compartilhado para reposição.",
      photos: [],
      invoice: "nf-mouses.pdf",
      maintenance: [],
      linkedProblems: [],
      tickets: [],
      lastCheck: "2026-06-15",
      replacementForecast: "",
      quantity: 12,
      available: 6,
      inUse: 5,
      defective: 1,
      minStock: 4,
      storage: "Armário TI"
    }
  ];

  const users = [
    { name: "Ana Martins", role: "Administrador", area: "Gestão de TI", status: "Ativo" },
    { name: "Mariana Lopes", role: "Gestor de TI", area: "Pré-impressão", status: "Ativo" },
    { name: "Rafael Nunes", role: "Técnico", area: "Infraestrutura", status: "Ativo" },
    { name: "Camila Rocha", role: "Atendente", area: "Comercial", status: "Ativo" },
    { name: "Bruno Alves", role: "Técnico", area: "Impressão digital", status: "Ativo" }
  ];

  return {
    categories,
    sectors,
    roles,
    checklists,
    problems,
    assets,
    users
  };
})();
